# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-ionampliseq-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc>=1.9
  - bioconda::samtools>=1.9
  - bioconda::bcftools>=1.9
  - bioconda::mash
  - bioconda::seqtk
  - bioconda::mosdepth
  - pigz
  - pip
  - pip:
    - attrs
    - biopython
    - numpy
    - pandas
    - seaborn
    - vcf_consensus_builder
    - xlrd
    - odfpy
