# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-ionampliseq-1.0.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::gcc_linux-64
  - conda-forge::cxx-compiler
  - conda-forge::markdown=3.1.1
  - conda-forge::pigz
  - conda-forge::pygments=2.5.2
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::python=3.7.3
  - conda-forge::wheel
  - bioconda::bcftools>=1.9
  - bioconda::fastqc=0.11.8
  - bioconda::mash
  - bioconda::mosdepth
  - bioconda::multiqc>=1.9
  - bioconda::samtools>=1.9
  - bioconda::seqtk
  - pip
  - pip:
    - attrs
    - biopython
    - edlib
    - numpy
    - odfpy
    - pandas
    - pysam
    - seaborn
    - vcf_consensus_builder
    - xlrd
