name: Bug Report
description: File a bug/issue
title: "[BUG]: "
labels: ["bug"]
assignees:
  - peterk87
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out and describe the issue(s) you've encountered! We'll try our best to help resolve your issues.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description of the Bug/Issue
      description: A clear and concise description of the issue you're experiencing.
      placeholder: |
        1. Updated to the latest version of the workflow with `nextflow pull`
        2. Prepared samplesheet.csv (see attached)
        3. Ran on HPC cluster with Slurm executor and Singularity container (`-profile slurm,singularity`)
        4. Encountered following error (see attached `.nextflow.log` file for more info)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Nextflow command-line
      description: Full `nextflow run ...` command-line.
      render: shell
      placeholder: nextflow run CFIA-NCFAD/nf-ionampliseq -profile docker ...
    validations:
      required: true
  - type: textarea
    id: error-message
    attributes:
      label: Error Message
      description: Please copy and paste the full error message you see in your terminal when running the workflow. Attaching the `.nextflow.log` would also help enormously.
      render: shell
      placeholder: |
        Oops... Pipeline execution stopped with the following message: null
        Error executing process > 'PROCESS'

        Caused by:
          Not a valid path value type: groovyx.gpars.dataflow.expression.DataflowGetPropertyExpression (DataflowGetPropertyExpression(value=null))

        Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
    validations:
      required: true
  - type: input
    id: wf-version
    attributes:
      label: Workflow Version
      description: Workflow version or Git commit hash
      placeholder: "v3.1.0; revision: 9473cbaed9"
    validations:
      required: true
  - type: input
    id: executor
    attributes:
      label: Nextflow Executor
      description: What [executor](https://www.nextflow.io/docs/latest/executor.html) was used to execute the workflow? (if you're not sure, you're likely using the `local` executor)
      placeholder: local, slurm, awsbatch, etc
    validations:
      required: false
  - type: input
    id: nextflow-version
    attributes:
      label: Nextflow Version
      description: What version of Nextflow were you running? Output from `nextflow -version`
      placeholder: "22.04.3"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Java Version
      description: What version of Java were you using? Output from `java -version`
      placeholder: |
        openjdk version "16.0.1" 2021-04-20
        OpenJDK Runtime Environment (build 16.0.1+9-24)
        OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
    validations:
      required: false
  - type: input
    attributes:
      label: Hardware
      description: What are you running the workflow on?
      placeholder: Desktop, HPC cluster, Cloud, etc
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System (OS)
      description: What OS are you running the workflow on?
      placeholder: Ubuntu 20.04 LTS
  - type: dropdown
    attributes:
      label: Conda/Container Engine
      description: Are you using a container engine or Conda?
      options:
        - Conda
        - Docker
        - Singularity
        - N/A (not using Conda or a container engine)
        - Charliecloud
        - Podman
        - Shifter
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here.

        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
