name: '✨ Feature request'
description: Suggest a new feature or enhancement for nf-ionampliseq
labels: [enhancement]

body:
  - id: description
    type: textarea
    attributes:
      label: Problem description
      description: >
        Please describe the feature or behavior you'd like to see in nf-ionampliseq and the motivation.
      placeholder: >
        I wish nf-ionampliseq could ...
    validations:
      required: true
